Hw 27.1 UserDaoHibernateImpl
Valdes2/internetshop_v2 pull request #10
Opened 2019-10-09 19:17 UTC by Valdes2

2019-10-10 15:52 UTC, boroda4436 approved these changes

2019-10-11 08:21 UTC, boroda4436 requested changes

2019-10-11 08:21 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/AddUserContrroller.java
> +    private static final Long USER = 3L;
@Valdes2 Може все таки прибрати це?

2019-10-11 08:21 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/AddUserContrroller.java
> +    private static final Long USER = 3L;
це хардкод

2019-10-11 08:21 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/hibernate/RoleDaoHibernateImpl.java
> +    public Set<Role> getAllRoles(Long userId) {
@Valdes2 треба пофіксити

2019-10-11 08:21 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +                    .createSQLQuery("INSERT INTO users_roles (role_id, user_id) VALUES (?, ?);");
@Valdes2 Ми можемо обійтися без явного інсерту а БД? Hibernate мав би робити це замість нас.

2019-10-11 08:21 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +    public List<Order> getUserOrders(Long userId) {
@Valdes2 може перенести в OrderDao?

2019-10-15 04:55 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/hibernate/RoleDaoHibernateImpl.java
> +    public Set<Role> getAllRoles(Long userId) {
fixed

2019-10-15 05:07 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +    public List<Order> getUserOrders(Long userId) {
Мы же по userId вытягиваем списки Orders для конкретного юзера, я думал логично что это в userDao находиться

2019-10-15 05:24 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +    public List<Order> getUserOrders(Long userId) {
перенес

2019-10-15 05:31 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +                    .createSQLQuery("INSERT INTO users_roles (role_id, user_id) VALUES (?, ?);");
Должен, но почему-то не делает, при чем связь каким-то обрзом строит

2019-10-15 06:52 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/hibernate/UserDaoHibernateImpl.java
> +                    .createSQLQuery("INSERT INTO users_roles (role_id, user_id) VALUES (?, ?);");
fixed

2019-10-15 06:53 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/controller/AddUserContrroller.java
> +    private static final Long USER = 3L;
fixed

2019-10-15 08:35 UTC, boroda4436 commented on .gitignore
> +/src/main/resources/log/
@Valdes2 Від корня прям? Може краще так?
```suggestion
src/main/resources/log/
```

2019-10-15 08:35 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +                //user.setBucketId(resultSet.getLong("bucket_id"));
@Valdes2 видали закоментований код, будь ласка

2019-10-15 08:49 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +                //user.setBucketId(resultSet.getLong("bucket_id"));
fixed

2019-10-15 08:54 UTC, merged

2019-10-15 09:11 UTC, Valdes2 commented on .gitignore
> +/src/main/resources/log/
fixed