added solution for homework 17.1_Logging
Valdes2/internetshop_v2 pull request #3
Opened 2019-09-19 17:18 UTC by Valdes2

2019-09-19 17:58 UTC, boroda4436 requested changes

2019-09-19 17:58 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/controller/InjectorInitializer.java
> +            logger.fatal("Injection was failed!", new RuntimeException(e));
```suggestion
            logger.fatal("Injection was failed!", e);
```

2019-09-19 22:15 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/controller/InjectorInitializer.java
> +            logger.fatal("Injection was failed!", new RuntimeException(e));
fixed

2019-09-20 05:47 UTC, boroda4436 approved these changes

2019-09-23 11:13 UTC, merged