added solution for homework 25.1_HashPassword
Valdes2/internetshop_v2 pull request #8
Opened 2019-10-06 09:33 UTC by Valdes2

2019-10-06 18:18 UTC, boroda4436 requested changes

2019-10-06 18:18 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/UserDao.java
> +    byte[] getSaltByLogin(String login);
@Valdes2 Ми можемо перенести цей метод в login(username, password)?

2019-10-06 18:18 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/impl/UserDaoImpl.java
> +        return new byte[0];
@Valdes2 Це трохи не корректно. Все одно метод getSalt ти використовуєш тільки при логіні

2019-10-06 18:18 UTC, boroda4436 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +    public byte[] getSaltByLogin(String login) {
чи можеш ти витягти просто користувача за логіном і в нього вже отримувати salt і hashpass?

2019-10-07 10:47 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/UserDao.java
> +    byte[] getSaltByLogin(String login);
окей, перенес логику в логин

2019-10-07 10:47 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/impl/UserDaoImpl.java
> +        return new byte[0];
окей, перенес логику в логин

2019-10-07 10:48 UTC, Valdes2 commented on src/main/java/mate/academy/internetshop/dao/jdbc/UserDaoJdbcImpl.java
> +    public byte[] getSaltByLogin(String login) {
В принципе можно, но ради вытягивания Salt по сути дублировать весь метод get?

2019-10-07 10:59 UTC, Sofasmile approved these changes

2019-10-07 11:06 UTC, merged